#! /bin/bash

# Start network manager and send ip address

sleep 40 # Wait
ifconfig wlan0 up  # Start adapter  
service networking restart # Restart networking
dhclient -r wlan0 # Release dhcp
dhclient wlan0 # Renew DHCP

ipv4="$(/sbin/ifconfig wlan0 | grep inet | head -n 1 | awk '{ print $2 }')" # >> /home/topazoo/store/temp/ip_addr
ipv6="$(/sbin/ifconfig wlan0 | grep inet6 | head -n 1 | awk '{ print $2 }')" # >> /home/topazoo/store/temp/ip_addr
python /home/YOURUSERNAME/store/python/wireless/textme.py $ipv4 $ipv6 # Text stored numbers

